import { generateSlug } from '@blog/utils'
import {
  Prisma,
} from '../generated/prisma/client/client'
import type {
  EventItem,
  EventSourceType,
  EventStatus,
  MediaAsset,
  PhotoEntry,
  Post,
  ProjectEntry,
  Thought,
} from '../generated/prisma/client/client'
import { prisma } from './db'
import {
  DATE_ONLY_RE,
  extractTitle,
  inferSourceType,
  inferStatus,
  parseExplicitDate,
} from './calendar-quick-create'

type EventAccessScope =
  | { mode: 'public' }
  | { mode: 'user'; userId: string }

type EventPayloadInput = Record<string, string | number | boolean | null>

type QuickCreateInput = {
  userId: string
  rawText: string
  defaultDate?: string
  sourceInputType: 'text' | 'voice'
}

export function dateStringToUtcDate(value: string): Date {
  if (!DATE_ONLY_RE.test(value)) {
    throw new Error('无效日期')
  }

  const date = new Date(`${value}T00:00:00.000Z`)
  if (Number.isNaN(date.getTime())) {
    throw new Error('无效日期')
  }

  return date
}

export function toDateString(value: Date): string {
  return value.toISOString().slice(0, 10)
}

function endOfUtcDay(value: string): Date {
  const start = dateStringToUtcDate(value)
  return new Date(start.getTime() + 24 * 60 * 60 * 1000 - 1)
}

function toIsoOrNull(value: Date | null | undefined): string | null {
  return value ? value.toISOString() : null
}

function toJsonPayload(payload: EventPayloadInput | null): Prisma.InputJsonValue | null {
  if (!payload) return null
  return payload
}

function buildPayloadWithJumpUrl(
  payload: EventPayloadInput | null,
  jumpUrl: string | null
): EventPayloadInput | null {
  if (!payload && !jumpUrl) return null
  return {
    ...(payload ?? {}),
    jumpUrl,
  }
}

function eventJumpUrlFromPayload(event: EventItem): string | null {
  if (!event.payloadJson || typeof event.payloadJson !== 'object' || Array.isArray(event.payloadJson)) {
    return null
  }

  const maybeUrl = (event.payloadJson as Record<string, unknown>).jumpUrl
  return typeof maybeUrl === 'string' ? maybeUrl : null
}

function defaultJumpUrlForEvent(event: EventItem): string | null {
  if (!event.sourceId) {
    return `/calendar/day/${toDateString(event.eventDate)}`
  }

  if (event.sourceType === 'post') {
    return `/blog/editor/${event.sourceId}`
  }
  if (event.sourceType === 'thought') {
    return `/thoughts/${event.sourceId}/edit`
  }
  if (event.sourceType === 'project') {
    return '/projects'
  }
  if (event.sourceType === 'photo') {
    return '/pictures'
  }

  return `/calendar/day/${toDateString(event.eventDate)}`
}

export function serializeEventItem(event: EventItem) {
  return {
    id: event.id,
    title: event.title,
    description: event.description ?? null,
    sourceType: event.sourceType,
    sourceId: event.sourceId ?? null,
    status: event.status,
    date: event.eventDate.toISOString(),
    endDate: toIsoOrNull(event.endDate),
    allDay: event.allDay,
    entryMethod: event.entryMethod,
    autoGenerated: event.autoGenerated,
    jumpUrl: eventJumpUrlFromPayload(event) ?? defaultJumpUrlForEvent(event),
    payload:
      event.payloadJson && typeof event.payloadJson === 'object' && !Array.isArray(event.payloadJson)
        ? (event.payloadJson as Record<string, unknown>)
        : null,
    createdAt: event.createdAt.toISOString(),
    updatedAt: event.updatedAt.toISOString(),
  }
}

export function serializeProjectEntry(project: ProjectEntry) {
  return {
    id: project.id,
    title: project.title,
    description: project.description ?? null,
    href: project.href ?? null,
    coverImage: project.coverImage ?? null,
    category: project.category ?? null,
    tags: Array.isArray(project.tags) ? (project.tags as string[]) : [],
    status: project.status,
    startedAt: toIsoOrNull(project.startedAt),
    createdAt: project.createdAt.toISOString(),
    updatedAt: project.updatedAt.toISOString(),
  }
}

function normalizeMediaVariants(value: unknown) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null
  return value as Record<string, unknown>
}

export function serializeMediaAsset(asset: MediaAsset) {
  return {
    id: asset.id,
    url: asset.url,
    storageKey: asset.storageKey,
    filename: asset.filename,
    mimeType: asset.mimeType,
    size: asset.size,
    width: asset.width ?? null,
    height: asset.height ?? null,
    variants: normalizeMediaVariants(asset.variants),
    source: asset.source,
    status: asset.status,
    createdAt: asset.createdAt.toISOString(),
    updatedAt: asset.updatedAt.toISOString(),
  }
}

export function serializePhotoEntry(photo: PhotoEntry & { mediaAsset?: MediaAsset | null }) {
  return {
    id: photo.id,
    title: photo.title ?? null,
    description: photo.description ?? null,
    imageUrl: photo.imageUrl ?? photo.mediaAsset?.url ?? null,
    mediaAssetId: photo.mediaAssetId ?? null,
    mediaAsset: photo.mediaAsset ? serializeMediaAsset(photo.mediaAsset) : null,
    takenAt: toIsoOrNull(photo.takenAt),
    createdAt: photo.createdAt.toISOString(),
    updatedAt: photo.updatedAt.toISOString(),
  }
}

async function findEventBySource(sourceType: EventSourceType, sourceId: string) {
  return prisma.eventItem.findFirst({
    where: {
      sourceType,
      sourceId,
    },
    orderBy: {
      createdAt: 'asc',
    },
  })
}

async function upsertLinkedEvent(input: {
  userId: string
  title: string
  description?: string | null
  sourceType: EventSourceType
  sourceId: string
  status: EventStatus
  eventDate: Date
  allDay?: boolean
  entryMethod?: string
  autoGenerated?: boolean
  payload?: EventPayloadInput | null
}) {
  const existing = await findEventBySource(input.sourceType, input.sourceId)
  const payloadJson = toJsonPayload(input.payload ?? null)
  const data: Prisma.EventItemUncheckedCreateInput = {
    userId: input.userId,
    title: input.title,
    description: input.description ?? null,
    sourceType: input.sourceType,
    sourceId: input.sourceId,
    status: input.status,
    eventDate: input.eventDate,
    allDay: input.allDay ?? true,
    entryMethod: input.entryMethod ?? 'manual',
    autoGenerated: input.autoGenerated ?? false,
  }
  if (payloadJson !== null) {
    data.payloadJson = payloadJson
  }

  if (existing) {
    return prisma.eventItem.update({
      where: { id: existing.id },
      data: {
        ...data,
        ...(payloadJson === null ? { payloadJson: Prisma.JsonNull } : {}),
      },
    })
  }

  return prisma.eventItem.create({
    data,
  })
}

export async function removeEventsForSource(sourceType: EventSourceType, sourceId: string) {
  await prisma.eventItem.deleteMany({
    where: {
      sourceType,
      sourceId,
    },
  })
}

export async function syncPostEvent(post: Post) {
  const jumpUrl = post.published ? `/posts/${post.slug || post.id}` : `/blog/editor/${post.id}`
  const payload = buildPayloadWithJumpUrl(
    {
      slug: post.slug || post.id,
      published: post.published,
    },
    jumpUrl
  )

  const existing = await findEventBySource('post', post.id)
  if (!post.published) {
    if (existing?.status === 'planned') {
      await prisma.eventItem.update({
        where: { id: existing.id },
        data: {
          title: post.title,
          description: post.excerpt ?? null,
          payloadJson: toJsonPayload(payload) ?? Prisma.JsonNull,
        },
      })
    } else if (existing?.autoGenerated) {
      await prisma.eventItem.delete({
        where: { id: existing.id },
      })
    }
    return
  }

  await upsertLinkedEvent({
    userId: post.authorId,
    title: post.title,
    description: post.excerpt ?? null,
    sourceType: 'post',
    sourceId: post.id,
    status: 'completed',
    eventDate: post.publishedAt ?? post.createdAt,
    allDay: true,
    entryMethod: 'system',
    autoGenerated: true,
    payload,
  })
}

function buildThoughtTitle(content: string): string {
  const condensed = content.replace(/\s+/g, ' ').trim()
  if (!condensed) return '记录想法'
  return (condensed.length > 48 ? `${condensed.slice(0, 48)}…` : condensed).slice(0, 120)
}

export async function syncThoughtEvent(thought: Thought) {
  if (!thought.authorId) return

  await upsertLinkedEvent({
    userId: thought.authorId,
    title: buildThoughtTitle(thought.content),
    description: thought.content.slice(0, 280) || null,
    sourceType: 'thought',
    sourceId: thought.id,
    status: 'completed',
    eventDate: thought.createdAt,
    allDay: true,
    entryMethod: 'system',
    autoGenerated: true,
    payload: buildPayloadWithJumpUrl(null, `/thoughts/${thought.id}/edit`),
  })
}

function mapProjectStatusToEventStatus(status: string): EventStatus {
  return status === 'planned' ? 'planned' : 'completed'
}

export async function syncProjectEvent(project: ProjectEntry) {
  if (!project.userId) return

  const jumpUrl = project.href?.trim() || '/projects'
  await upsertLinkedEvent({
    userId: project.userId,
    title: project.title,
    description: project.description ?? null,
    sourceType: 'project',
    sourceId: project.id,
    status: mapProjectStatusToEventStatus(project.status),
    eventDate: project.startedAt ?? project.createdAt,
    allDay: true,
    entryMethod: 'manual',
    autoGenerated: true,
    payload: buildPayloadWithJumpUrl(
      {
        href: project.href ?? null,
        status: project.status,
      },
      jumpUrl
    ),
  })
}

export async function syncPhotoEvent(photo: PhotoEntry) {
  if (!photo.userId) return

  await upsertLinkedEvent({
    userId: photo.userId,
    title: photo.title?.trim() || '新增照片',
    description: photo.description ?? null,
    sourceType: 'photo',
    sourceId: photo.id,
    status: photo.imageUrl ? 'completed' : 'planned',
    eventDate: photo.takenAt ?? photo.createdAt,
    allDay: true,
    entryMethod: 'manual',
    autoGenerated: true,
    payload: buildPayloadWithJumpUrl(
      {
        imageUrl: photo.imageUrl ?? null,
      },
      '/pictures'
    ),
  })
}

export async function createManualEvent(input: {
  userId: string
  title: string
  description?: string | null
  date: string
  status: EventStatus
  allDay?: boolean
  sourceType?: EventSourceType
}) {
  return prisma.eventItem.create({
    data: {
      userId: input.userId,
      title: input.title,
      description: input.description ?? null,
      sourceType: input.sourceType ?? 'manual',
      status: input.status,
      eventDate: dateStringToUtcDate(input.date),
      allDay: input.allDay ?? true,
      entryMethod: 'manual',
      autoGenerated: false,
    },
  })
}

export async function updateEventItemById(input: {
  id: string
  userId: string
  title?: string
  description?: string | null
  date?: string
  status?: EventStatus
  allDay?: boolean
}) {
  const existing = await prisma.eventItem.findUnique({
    where: { id: input.id },
  })
  if (!existing) return null
  if (existing.userId !== input.userId) return 'forbidden' as const

  return prisma.eventItem.update({
    where: { id: input.id },
    data: {
      ...(input.title !== undefined ? { title: input.title } : {}),
      ...(input.description !== undefined ? { description: input.description } : {}),
      ...(input.date !== undefined ? { eventDate: dateStringToUtcDate(input.date) } : {}),
      ...(input.status !== undefined ? { status: input.status } : {}),
      ...(input.allDay !== undefined ? { allDay: input.allDay } : {}),
    },
  })
}

function buildScopeWhere(scope: EventAccessScope): Prisma.EventItemWhereInput {
  if (scope.mode === 'user') {
    return { userId: scope.userId }
  }

  return {
    status: 'completed',
    sourceType: {
      in: ['post', 'thought', 'project', 'photo'],
    },
  }
}

export async function getCalendarSummary(
  scope: EventAccessScope,
  params: {
    from?: string
    to?: string
  }
) {
  const where: Prisma.EventItemWhereInput = {
    ...buildScopeWhere(scope),
  }

  if (params.from || params.to) {
    where.eventDate = {}
    if (params.from) {
      where.eventDate.gte = dateStringToUtcDate(params.from)
    }
    if (params.to) {
      where.eventDate.lte = endOfUtcDay(params.to)
    }
  }

  const [events, annotations] = await Promise.all([
    prisma.eventItem.findMany({
      where,
      orderBy: [{ eventDate: 'asc' }, { createdAt: 'asc' }],
    }),
    scope.mode === 'user'
      ? prisma.calendarAnnotation.findMany({
          where: {
            userId: scope.userId,
            ...(params.from || params.to
              ? {
                  date: {
                    ...(params.from ? { gte: dateStringToUtcDate(params.from) } : {}),
                    ...(params.to ? { lte: dateStringToUtcDate(params.to) } : {}),
                  },
                }
              : {}),
          },
          orderBy: { date: 'asc' },
        })
      : Promise.resolve([]),
  ])

  const grouped = new Map<
    string,
    {
      totalCount: number
      plannedCount: number
      completedCount: number
      canceledCount: number
      sourceTypes: Set<EventSourceType>
      annotationLabel: string | null
    }
  >()

  for (const event of events) {
    const key = toDateString(event.eventDate)
    const current =
      grouped.get(key) ??
      {
        totalCount: 0,
        plannedCount: 0,
        completedCount: 0,
        canceledCount: 0,
        sourceTypes: new Set<EventSourceType>(),
        annotationLabel: null,
      }

    current.totalCount += 1
    current.sourceTypes.add(event.sourceType)
    if (event.status === 'planned') current.plannedCount += 1
    if (event.status === 'completed') current.completedCount += 1
    if (event.status === 'canceled') current.canceledCount += 1
    grouped.set(key, current)
  }

  for (const annotation of annotations) {
    const key = toDateString(annotation.date)
    const current =
      grouped.get(key) ??
      {
        totalCount: 0,
        plannedCount: 0,
        completedCount: 0,
        canceledCount: 0,
        sourceTypes: new Set<EventSourceType>(),
        annotationLabel: null,
      }
    current.annotationLabel = annotation.label
    grouped.set(key, current)
  }

  return [...grouped.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([date, summary]) => ({
      date,
      totalCount: summary.totalCount,
      plannedCount: summary.plannedCount,
      completedCount: summary.completedCount,
      canceledCount: summary.canceledCount,
      annotationLabel: summary.annotationLabel,
      sourceTypes: [...summary.sourceTypes],
    }))
}

export async function getCalendarEventList(
  scope: EventAccessScope,
  params: {
    from?: string
    to?: string
  }
) {
  const where: Prisma.EventItemWhereInput = {
    ...buildScopeWhere(scope),
  }

  if (params.from || params.to) {
    where.eventDate = {}
    if (params.from) {
      where.eventDate.gte = dateStringToUtcDate(params.from)
    }
    if (params.to) {
      where.eventDate.lte = endOfUtcDay(params.to)
    }
  }

  const events = await prisma.eventItem.findMany({
    where,
    orderBy: [{ eventDate: 'asc' }, { createdAt: 'asc' }],
  })

  return events.map(serializeEventItem)
}

export async function getCalendarDay(
  scope: EventAccessScope,
  date: string
) {
  const [events, annotation] = await Promise.all([
    prisma.eventItem.findMany({
      where: {
        ...buildScopeWhere(scope),
        eventDate: {
          gte: dateStringToUtcDate(date),
          lte: endOfUtcDay(date),
        },
      },
      orderBy: [{ eventDate: 'asc' }, { createdAt: 'asc' }],
    }),
    scope.mode === 'user'
      ? prisma.calendarAnnotation.findUnique({
          where: {
            userId_date: {
              userId: scope.userId,
              date: dateStringToUtcDate(date),
            },
          },
        })
      : Promise.resolve(null),
  ])

  const summary = {
    date,
    totalCount: events.length,
    plannedCount: events.filter((event) => event.status === 'planned').length,
    completedCount: events.filter((event) => event.status === 'completed').length,
    canceledCount: events.filter((event) => event.status === 'canceled').length,
    annotationLabel: annotation?.label ?? null,
    sourceTypes: [...new Set(events.map((event) => event.sourceType))],
  }

  return {
    date,
    summary,
    annotation: annotation
      ? {
          id: annotation.id,
          date: toDateString(annotation.date),
          label: annotation.label,
          createdAt: annotation.createdAt.toISOString(),
          updatedAt: annotation.updatedAt.toISOString(),
        }
      : null,
    events: events.map(serializeEventItem),
  }
}

export async function createQuickCalendarEntry(input: QuickCreateInput) {
  const now = new Date()
  const inferredSourceType = inferSourceType(input.rawText)
  const targetDate = parseExplicitDate(input.rawText, now) ?? input.defaultDate ?? toDateString(now)
  const inferredStatus = inferStatus(input.rawText, inferredSourceType, targetDate, now)
  const title = extractTitle(input.rawText, inferredSourceType)
  const normalizedDescription = input.rawText.trim()

  if (inferredSourceType === 'post') {
    let slugBase = generateSlug(title)
    if (!slugBase) {
      slugBase = `post-${Date.now()}`
    }

    const existing = await prisma.post.findUnique({
      where: { slug: slugBase },
      select: { id: true },
    })

    const slug = existing ? `${slugBase}-${Date.now()}` : slugBase
    const post = await prisma.post.create({
      data: {
        authorId: input.userId,
        slug,
        title,
        content: normalizedDescription,
        published: false,
      },
    })

    const event = await upsertLinkedEvent({
      userId: input.userId,
      title,
      description: normalizedDescription,
      sourceType: 'post',
      sourceId: post.id,
      status: 'planned',
      eventDate: dateStringToUtcDate(targetDate),
      allDay: true,
      entryMethod: input.sourceInputType === 'voice' ? 'ai_voice' : 'ai_text',
      autoGenerated: false,
      payload: buildPayloadWithJumpUrl(
        {
          slug: post.slug,
          published: false,
        },
        `/blog/editor/${post.id}`
      ),
    })

    return {
      event: serializeEventItem(event),
      inferredSourceType,
      inferredStatus: 'planned' as EventStatus,
      targetDate,
      linkedEntity: {
        type: 'post' as const,
        id: post.id,
        jumpUrl: `/blog/editor/${post.id}`,
      },
      note: '已创建博客草稿，并关联到对应日期。出于保守策略，不会直接自动发布。',
    }
  }

  if (inferredSourceType === 'thought') {
    const thought = await prisma.thought.create({
      data: {
        authorId: input.userId,
        content: normalizedDescription,
        images: [],
      },
    })

    const event = await upsertLinkedEvent({
      userId: input.userId,
      title: buildThoughtTitle(normalizedDescription),
      description: normalizedDescription,
      sourceType: 'thought',
      sourceId: thought.id,
      status: inferredStatus,
      eventDate: dateStringToUtcDate(targetDate),
      allDay: true,
      entryMethod: input.sourceInputType === 'voice' ? 'ai_voice' : 'ai_text',
      autoGenerated: false,
      payload: buildPayloadWithJumpUrl(null, `/thoughts/${thought.id}/edit`),
    })

    return {
      event: serializeEventItem(event),
      inferredSourceType,
      inferredStatus,
      targetDate,
      linkedEntity: {
        type: 'thought' as const,
        id: thought.id,
        jumpUrl: `/thoughts/${thought.id}/edit`,
      },
      note: inferredStatus === 'planned' ? '已记录想法，并作为计划事件挂到对应日期。' : '已记录想法并聚合到当天事件流。',
    }
  }

  if (inferredSourceType === 'project') {
    const project = await prisma.projectEntry.create({
      data: {
        userId: input.userId,
        title,
        description: normalizedDescription,
        status: inferredStatus === 'planned' ? 'planned' : 'active',
        startedAt: dateStringToUtcDate(targetDate),
      },
    })

    const event = await upsertLinkedEvent({
      userId: input.userId,
      title,
      description: normalizedDescription,
      sourceType: 'project',
      sourceId: project.id,
      status: inferredStatus,
      eventDate: project.startedAt ?? project.createdAt,
      allDay: true,
      entryMethod: input.sourceInputType === 'voice' ? 'ai_voice' : 'ai_text',
      autoGenerated: false,
      payload: buildPayloadWithJumpUrl(
        {
          status: project.status,
        },
        '/projects'
      ),
    })

    return {
      event: serializeEventItem(event),
      inferredSourceType,
      inferredStatus,
      targetDate,
      linkedEntity: {
        type: 'project' as const,
        id: project.id,
        jumpUrl: '/projects',
      },
      note: '已创建项目记录，并加入当日事件流。',
    }
  }

  if (inferredSourceType === 'photo') {
    const photo = await prisma.photoEntry.create({
      data: {
        userId: input.userId,
        title,
        description: normalizedDescription,
        takenAt: dateStringToUtcDate(targetDate),
      },
    })

    const event = await upsertLinkedEvent({
      userId: input.userId,
      title,
      description: normalizedDescription,
      sourceType: 'photo',
      sourceId: photo.id,
      status: inferredStatus,
      eventDate: photo.takenAt ?? photo.createdAt,
      allDay: true,
      entryMethod: input.sourceInputType === 'voice' ? 'ai_voice' : 'ai_text',
      autoGenerated: false,
      payload: buildPayloadWithJumpUrl(null, '/pictures'),
    })

    return {
      event: serializeEventItem(event),
      inferredSourceType,
      inferredStatus,
      targetDate,
      linkedEntity: {
        type: 'photo' as const,
        id: photo.id,
        jumpUrl: '/pictures',
      },
      note: '已先记录一条照片事项。若要真正展示图片，可稍后在今日事件页上传文件补全。',
    }
  }

  const event = await createManualEvent({
    userId: input.userId,
    title,
    description: normalizedDescription,
    date: targetDate,
    status: inferredStatus,
    allDay: true,
    sourceType: 'manual',
  })

  return {
    event: serializeEventItem(event),
    inferredSourceType,
    inferredStatus,
    targetDate,
    linkedEntity: null,
    note: '已按通用事件记录，后续可在当天页继续补充细节或改为具体业务项。',
  }
}
