import { randomBytes } from 'node:crypto'
import { Prisma } from '../generated/prisma/client/client'
import type {
  EventStatus,
  PlanItem,
  PlanItemStatus,
  PlanShareLink,
  PlanSpace,
} from '../generated/prisma/client/client'
import { prisma } from './db'
import { dateStringToUtcDate, toDateString } from './calendar-events'

type PlanSpaceWithRelations = PlanSpace & {
  items?: PlanItem[]
  shareLinks?: PlanShareLink[]
}

type PlanItemWithSpace = PlanItem & {
  space: PlanSpace
}

export function createShareToken() {
  return randomBytes(18).toString('base64url')
}

export function serializePlanItem(item: PlanItem) {
  return {
    id: item.id,
    spaceId: item.spaceId,
    title: item.title,
    description: item.description ?? null,
    date: toDateString(item.date),
    startTime: item.startTime ?? null,
    endTime: item.endTime ?? null,
    allDay: item.allDay,
    status: item.status,
    priority: item.priority,
    assignee: item.assignee ?? null,
    category: item.category ?? null,
    isMilestone: item.isMilestone,
    syncedEventId: item.syncedEventId ?? null,
    sortOrder: item.sortOrder,
    createdAt: item.createdAt.toISOString(),
    updatedAt: item.updatedAt.toISOString(),
  }
}

export function serializePlanShareLink(link: PlanShareLink) {
  return {
    id: link.id,
    spaceId: link.spaceId,
    token: link.token,
    permission: link.permission,
    expiresAt: link.expiresAt?.toISOString() ?? null,
    createdAt: link.createdAt.toISOString(),
    updatedAt: link.updatedAt.toISOString(),
  }
}

export function serializePlanSpace(space: PlanSpaceWithRelations) {
  const items = [...(space.items ?? [])].sort(comparePlanItems)
  const doneCount = items.filter((item) => item.status === 'done').length
  const nextItem = items.find((item) => !['done', 'canceled'].includes(item.status)) ?? null

  return {
    id: space.id,
    title: space.title,
    type: space.type,
    icon: space.icon,
    description: space.description ?? null,
    status: space.status,
    startDate: space.startDate ? toDateString(space.startDate) : null,
    endDate: space.endDate ? toDateString(space.endDate) : null,
    collaborationOn: space.collaborationOn,
    shareToken: space.shareToken,
    itemCount: items.length,
    doneCount,
    milestoneCount: items.filter((item) => item.isMilestone).length,
    nextItem: nextItem ? serializePlanItem(nextItem) : null,
    items: items.map(serializePlanItem),
    shareLinks: (space.shareLinks ?? []).map(serializePlanShareLink),
    createdAt: space.createdAt.toISOString(),
    updatedAt: space.updatedAt.toISOString(),
  }
}

export async function syncPlanItemMilestone(item: PlanItemWithSpace) {
  if (!item.isMilestone) {
    await deleteSyncedMilestone(item)
    return null
  }

  const payload = {
    planSpaceId: item.spaceId,
    planItemId: item.id,
    planSpaceTitle: item.space.title,
    jumpUrl: `/plans/${item.spaceId}`,
  }
  const eventStatus = mapPlanItemStatusToEventStatus(item.status)
  const eventDate = buildEventDate(item.date, item.startTime)
  const description = [
    item.description?.trim() || null,
    item.assignee ? `负责人：${item.assignee}` : null,
    item.category ? `分类：${item.category}` : null,
  ].filter(Boolean).join('\n')

  if (item.syncedEventId) {
    return prisma.eventItem.update({
      where: { id: item.syncedEventId },
      data: {
        userId: item.space.ownerId,
        title: item.title,
        description: description || null,
        sourceType: 'system',
        sourceId: item.id,
        status: eventStatus,
        eventDate,
        allDay: item.allDay,
        entryMethod: 'plan_space',
        autoGenerated: true,
        payloadJson: payload,
      },
    })
  }

  const event = await prisma.eventItem.create({
    data: {
      userId: item.space.ownerId,
      title: item.title,
      description: description || null,
      sourceType: 'system',
      sourceId: item.id,
      status: eventStatus,
      eventDate,
      allDay: item.allDay,
      entryMethod: 'plan_space',
      autoGenerated: true,
      payloadJson: payload,
    },
  })

  await prisma.planItem.update({
    where: { id: item.id },
    data: { syncedEventId: event.id },
  })

  return event
}

export async function deleteSyncedMilestone(item: Pick<PlanItem, 'id' | 'syncedEventId'>) {
  if (!item.syncedEventId) return

  await prisma.planItem.update({
    where: { id: item.id },
    data: { syncedEventId: null },
  })
  await prisma.eventItem.deleteMany({
    where: {
      id: item.syncedEventId,
      entryMethod: 'plan_space',
    },
  })
}

export function buildPlanItemWhere(spaceId: string, params: {
  status?: PlanItemStatus
  from?: string
  to?: string
  milestone?: 'true' | 'false'
}) {
  const where: Prisma.PlanItemWhereInput = { spaceId }

  if (params.status) where.status = params.status
  if (params.milestone) where.isMilestone = params.milestone === 'true'
  if (params.from || params.to) {
    where.date = {
      ...(params.from ? { gte: dateStringToUtcDate(params.from) } : {}),
      ...(params.to ? { lte: dateStringToUtcDate(params.to) } : {}),
    }
  }

  return where
}

function comparePlanItems(left: PlanItem, right: PlanItem) {
  return (
    left.date.getTime() - right.date.getTime() ||
    (left.startTime ?? '').localeCompare(right.startTime ?? '') ||
    left.sortOrder - right.sortOrder ||
    left.createdAt.getTime() - right.createdAt.getTime()
  )
}

function mapPlanItemStatusToEventStatus(status: PlanItemStatus): EventStatus {
  if (status === 'done') return 'completed'
  if (status === 'canceled') return 'canceled'
  return 'planned'
}

function buildEventDate(date: Date, startTime: string | null) {
  if (!startTime) return date
  const datePart = toDateString(date)
  return new Date(`${datePart}T${startTime}:00.000Z`)
}
