export type CalendarEventSourceType =
  | 'manual'
  | 'post'
  | 'thought'
  | 'project'
  | 'photo'
  | 'system'

export type CalendarEventStatus = 'planned' | 'completed' | 'canceled'

export interface CalendarAnnotationSummary {
  id: string
  date: string
  label: string
  createdAt: string
  updatedAt: string
}

export interface CalendarEventDto {
  id: string
  title: string
  description: string | null
  sourceType: CalendarEventSourceType
  sourceId: string | null
  status: CalendarEventStatus
  date: string
  endDate: string | null
  allDay: boolean
  entryMethod: string
  autoGenerated: boolean
  jumpUrl: string | null
  payload: Record<string, unknown> | null
  createdAt: string
  updatedAt: string
}

export interface CalendarDaySummaryDto {
  date: string
  totalCount: number
  plannedCount: number
  completedCount: number
  canceledCount: number
  annotationLabel: string | null
  sourceTypes: CalendarEventSourceType[]
}

export interface CalendarDayResponse {
  date: string
  summary: CalendarDaySummaryDto
  annotation: CalendarAnnotationSummary | null
  events: CalendarEventDto[]
}

export interface CalendarQuickCreateResult {
  event: CalendarEventDto
  inferredSourceType: CalendarEventSourceType
  inferredStatus: CalendarEventStatus
  targetDate: string
  linkedEntity:
    | {
        type: 'post' | 'thought' | 'project' | 'photo'
        id: string
        jumpUrl: string | null
      }
    | null
  note: string
}

export interface ProjectEntryDto {
  id: string
  title: string
  description: string | null
  href: string | null
  coverImage: string | null
  category: string | null
  tags: string[]
  status: string
  startedAt: string | null
  createdAt: string
  updatedAt: string
}

export interface PhotoEntryDto {
  id: string
  title: string | null
  description: string | null
  imageUrl: string | null
  takenAt: string | null
  createdAt: string
  updatedAt: string
}
