import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useEffect } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { TimelineStudio } from "./components/timeline/TimelineStudio";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { useTimelinePlayback } from "./hooks/useTimelinePlayback";
import { CHAPTERS } from "./registry/chapters";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

export default function App() {
  const urlParams =
    typeof window === "undefined" ? new URLSearchParams() : new URLSearchParams(window.location.search);
  const studioMode = urlParams.get("studio") === "1";
  const timelineMode =
    urlParams.get("bgm") === "1" ||
    (urlParams.get("auto") === "1" && urlParams.get("timeline") === "1");
  const stepper = useStepper(CHAPTERS, { keyboardEnabled: !studioMode });
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();
  const timelineActive = timelineMode && !studioMode;

  useEffect(() => {
    if (!timelineActive || autoStarted) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.target instanceof HTMLInputElement) return;
      if (event.key === " ") {
        event.preventDefault();
        setAutoStarted(true);
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [autoStarted, setAutoStarted, timelineActive]);

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioSrc =
    timelineActive || mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  const { error: timelineError } = useTimelinePlayback({
    chapters: CHAPTERS,
    enabled: timelineActive,
    autoStarted,
    onJump: stepper.jumpToChapter,
  });

  const stage = (
    <Stage onAdvance={stepper.next} fitToContainer={studioMode}>
      <div key={ch.id} className="scene">
        <Cmp step={stepper.cursor.step} />
      </div>
    </Stage>
  );

  if (studioMode) {
    return (
      <TimelineStudio
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      >
        {stage}
      </TimelineStudio>
    );
  }

  return (
    <>
      {stage}
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      {timelineError ? <div className="timeline-runtime-error">{timelineError}</div> : null}
      <AutoStartGate
        visible={(mode === "auto" || timelineActive) && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
    </>
  );
}
