import { prisma } from '../src/lib/db'
import {
  syncPhotoEvent,
  syncPostEvent,
  syncProjectEvent,
  syncThoughtEvent,
} from '../src/lib/calendar-events'

async function main() {
  console.log('[backfill-events] resetting auto-generated event items')

  await prisma.eventItem.deleteMany({
    where: {
      autoGenerated: true,
      sourceType: {
        in: ['post', 'thought', 'project', 'photo'],
      },
    },
  })

  const [posts, thoughts, projects, photos] = await Promise.all([
    prisma.post.findMany({
      where: { published: true },
      orderBy: { createdAt: 'asc' },
    }),
    prisma.thought.findMany({
      where: { authorId: { not: null } },
      orderBy: { createdAt: 'asc' },
    }),
    prisma.projectEntry.findMany({
      where: { userId: { not: null } },
      orderBy: { createdAt: 'asc' },
    }),
    prisma.photoEntry.findMany({
      where: { userId: { not: null } },
      orderBy: { createdAt: 'asc' },
    }),
  ])

  for (const post of posts) {
    await syncPostEvent(post)
  }
  for (const thought of thoughts) {
    await syncThoughtEvent(thought)
  }
  for (const project of projects) {
    await syncProjectEvent(project)
  }
  for (const photo of photos) {
    await syncPhotoEvent(photo)
  }

  console.log(
    `[backfill-events] finished: posts=${posts.length}, thoughts=${thoughts.length}, projects=${projects.length}, photos=${photos.length}`
  )
}

main()
  .catch((error) => {
    console.error('[backfill-events] failed:', error)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
